### ISSUE TITLE
Lyno - Voice Rooms/Channels

### ISSUE THREAD

**Issue by sapkra** [mattermost/mattermost-marketplace#162]
#### Summary
This plugin provides a direct integration of voice channels into Mattermost. I developed this plugin within the Jitsi+Mattermost hackathon and found some time now to submit it for the marketplace.

![image](https://user-images.githubusercontent.com/8087568/105793595-b1053980-5f89-11eb-8ff2-baf542182d60.png)

#### Review commit
It's not possible to build it right now but we will publish the necessary npm packages soon and will comment on this issue but you can already review the code and latest build.
https://github.com/lynoapp/mattermost-plugin-lyno

## Checklist

**Product requirements**

- [x] The plugin is published under an [Open Source license](https://opensource.org/licenses/alphabetical).
- [x] The source code is available in a public git repository.
- [x] There is a public issue or bug tracker for the plugin, which is linked in the plugin documentation and linked via `support_url` in the manifest.
- [ ] The plugin provides detailed usage documentation with at least one screenshot of the plugin in action, list of features, and a development guide. This is typically a `README` file or a landing page on the web. The link to the documentation is set as `homepage_url` in the manifest. A great example is the [`README` of the GitHub plugin](https://github.com/mattermost/mattermost-plugin-github/blob/master/README.md).
- [x] For the current release and upcoming ones a changelog has to be published, with a link recorded in the `release_notes_url` property of the `plugin.json` manifest.
- [x] The plugin has to be out of Beta and be released with at least v1.0.0.
- [x] All configuration is accessible via the Mattermost UI.
- [x] The plugin ID defined in the manifest must not collide with the ID of an existing plugin in the Marketplace. It should follow [the documentation's suggested naming convention](https://developers.mattermost.com/extend/plugins/manifest-reference/#id).

**Technical requirements**

- [x] The plugin works for 60k concurrent connections and in a high-availability deployment. **Note:** There are currently no publicly-available tools to verify these properties. As such, they are checked during code review by a developer.
- [x] The plugin logs important events on appropriate log levels to allow System Admins to troubleshoot issues.

**Security requirements**

- [ ] Security reviews do not reveal any exploitable vulnerabilities in the plugin.
- [x] The plugin provides an email address or a username on the [Community Server](https://community.mattermost.com) used to report vulnerabilities in the future. Please post it into this issue or send it to ben.schumacher@mattermost.com.

**Functional requirements**

- [x] The plugin must set a `min_server_version` in the manifest.
- [x] The plugin must work on all Mattermost versions greater than or equal to the `min_server_version`.

## Security contact
Paul Tiedtke
paul@lyno.io

## TODO
- [ ] Add development guide
- [ ] Publish lyno dependencies on npm

## Questions
Who will do the security review? The Mattermost team? Or should we do it internally? I think it would make more sense to have an outside entity looking into it.

**Comment by aaronrothschild** [comment]
@sapkra Thanks for submitting to the marketplace.  I was just telling @adamjclarkson about your solution yesterday in fact.  

Our security team will perform a review, we've got a few submissions in the hopper so that team is a bit backed up but they'll add comments to your repo.  

I had an issue the other day with the Lyno plugin I believe - it was causing the whole UI to disappear - here's the console: 
![image](https://user-images.githubusercontent.com/915956/105854012-2b8a8500-5f9b-11eb-9b9d-52fb527b0132.png)

Obviously, we want to avoid this type of interference (because there's no easy way to disable the plugin if the whole UI is crashing).  This is partly also because of the power of plugins, that we can cause errors too. 

cc @hanzei @jasonblais

**Comment by sapkra** [comment]
Thank you for your report. I will look into it. And will try to avoid them completely.

The best way for a plugin system is to force them to be in an iframe and add an permission system for the data similar to oauth scopes. It would be definitely more stable and secure but has of course other disadvantages. The plugin system of monday.com is a good example how to can look like.

**Comment by hanzei** [comment]
Hey @sapkra,

Thanks for submitting your plugin :tada: I will queue it for code review.

**Comment by hanzei** [comment]
The checklist below will be used to track the process of getting your plugin to the Marketplace. It's sole purpose it visibility.

## Process checklist
- [ ] Create a private fork under the Mattermost organization; `master` should only contain a `README.md`.
- [ ] Give submitter read access to the fork.
- [ ] Create PR to merge upstream into `master`.
- [ ] Request reviews.
- [ ] [Cut plugin release](https://developers.mattermost.com/internal/plugin-release-process).
- [ ] Add release to Marketplace.
- [ ] Reach out on [Marketing Channel](https://community-release.mattermost.com/private-core/channels/marketing) to tweet about the plugin.
- [ ] Work with `@hanna.park` regarding swag.
